---
kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      dockerfile: docker/Dockerfile
      context: docker
      platforms:
        - linux/amd64
        - linux/arm64